[package]
name = "rustic-garden"
version = "0.1.0"
authors = ["rcrobert"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysfs_gpio = "0.5"
signal-hook = "0.1.15"
